---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

### Unit Testing


Notes on Unit Testing in Python

```{python}
import src.calc as calc
```

The `calc` module offers a few math functions which we'll test to see it they work.

```{python}
calc.add(4,5)
```

within `src/test_calc.py` we have the unit testing module, which some code to test the first function in `calc`

```{python active="", eval=FALSE}
import unittest
import calc

class TestCalc(unittest.TestCase):
    
    def test_add(self):
        result = calc.add(10,5)
        self.assertEqual(result, 15)
        
if __name__ == "__main__":
    unittest.main()
```

```{python active="", eval=FALSE}
Notice `line 10` which calls unittest.main() when the module is called directly like below.
```

```{python}
# ! python ./src/test_calc.py
```

There are 4 tests inside the `test_calc.py` file, their successful run is represented as a dot `.` in the terminal.


this is to prevent having to write the below which makes automating testing awkward:

```{python active="", eval=FALSE}
! python -m unittest ./src/test_calc.py
```

```{python active="", eval=FALSE}
[...]

    def test_divide(self):
    
        result = calc.divide(10,5)
        self.assertEqual(result, 2)
       
        self.assertRaises(ZeroDivisionError, calc.divide, 10, 0)
        
[...]
```

You can have multiple assertions under the same test, although it may be harder to tell which of those tests failed. The example above also shows how you can use the `assertRaises` function to see if the correct error is thrown.


You can also use a Context Manager to assert this test:

```{python active="", eval=FALSE}
[...] 

    def test_divide(self):
    
        with self.assertRaises(ZeroDivisionError):
            calc.divide(10,0)
    
[...]
```

```{python}

```
